sudo: require
services:
    - docker


before_install:
    - docker build -t stuckincallback/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true stuckincallback/docker-react npm run test -- --coverage